#image: lpmn/minke:latest
image: python
stages:
  - test
  - build
  - deploy

# test-python27:
#   stage: test
#   script:
#     - export PYTHONPATH="/usr/local/lib64/python2.7/site-packages"
#     - echo "pandas" > requirements.txt
#     - pip install -r requirements.txt
#     - pip install coverage
#     - python setup.py install
#     - coverage run setup.py test
#     - coverage report -m
#     #- coverage html	
#     #- mv htmlcov public/coverage
#   coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
#   artifacts:
#     expire_in: 3h
#     paths:
#       - testout
#       - public

test-python-36:
  stage: test
  image: python:3.6
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install
    - coverage run setup.py test
    - coverage report -m
  allow_failure: true

test-python-37:
  stage: test
  image: python:3.7
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - python setup.py install
    - coverage run setup.py test
    - coverage report -m
  allow_failure: true

pages:
  stage: build
  script:
  - pip install -r requirements.txt
  - pip install .
  - pip install sphinx numpydoc  kentigern # sphinxcontrib-versioning
  - pip install -r requirements_dev.txt
  - make docs
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master


# # Build receipe for standalone wheels on Linux
# wheel-27:
#   image: python:2.7
#   stage: build
#   script:
#     - pip install wheel
#     # Build wheel
#     - python setup.py bdist_wheel --universal
#   dependencies: []
#   artifacts:
#     expire_in: 3h
#     paths:
#       - dist

wheel-36:
  image: python:3.6
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist

wheel-37:
  image: python:3.7
  stage: build
  script:
    - pip install wheel
    # Build wheel
    - python setup.py bdist_wheel --universal
  dependencies: []
  artifacts:
    expire_in: 3h
    paths:
      - dist

deploy:wheel:
  stage: deploy
  script:
    - pip install twine
    - twine upload dist/*
  only:
    #- master@daniel-williams/minke
    - tags
  # except:
  #   - pushes
  #   - web
